/**
 * Generated by `pnpm helix:catalogue`. Do not edit by hand.
 *
 * Curated display names only, from data/model-names.json. Kept separate from
 * the full catalogue so the UI can name a block without bundling every
 * parameter of every model.
 *
 * 0 model(s) named.
 */

export interface ModelName {
  label?: string;
  basedOn?: string;
  category?: string;
}

export const MODEL_NAMES: Readonly<Record<string, ModelName>> = {};
